#%RAML 1.0
title: CourseDetails
description: Course Details 

/AboutMulesoft:
  post:
    body:
      application/json:
        example:
          {"Message": "Mulesoft is middleware technology.Easy and interesting to Learn"}
    responses:
      200:
        body:
          application/json:
            example:
              {"message":"Info about Mulesoft displayed successfully"}
      400:
        body:
          application/json:
            example:
              {"message":"Client side errors are getting"}  
      500:
        body:
          application/json:
            example:
              {"message":"Getting Server side errors"}        